### PR TITLE
ReviseURLs for fetching ISL and gcc

### PR DESCRIPTION
**Pull request by Mike4Online**

### CODE REVIEW

**Review by Mike4Online — COMMENTED** [review]
Updated URLs for fetching ISL and GCC

**Comment by darrenjs** [comment]
thanks for fix!

**Comment by Mike4Online** [comment]
You're welcome.  Thanks for the script!

Incidentally, I wound up installing GCC 9.4.0 (on my Ubuntu 18.04 development computer) rather than using your script to build GCC 9.5.0.  I successfully built GCC 9.5.0 with your script, but I was not confident I could install GCC 9.5.0 in the various system folders so it would be as if I had installed it from a standard Ubuntu repository via Apt.

But even after installing GCC 9.4.0 using [this procedure](https://gist.github.com/alexandreelise/192a63e287018ddfc896bbcb70b219d4) my application runs only on _some_ Linux distributions, while it fails to initialize on other versions of Linux such as Ubuntu 18.04.  I suspect this is due to outdated libstdc++.so versions on the target system.  Perhaps I need to statically link to the newer libstdc++ that comes with GCC 9.4.0, or somehow modify my .deb installer to fetch the newer libstdc++ as an installation dependency.  I am pretty clueless about either approach.

I'd be grateful for any suggestions.

Thanks again.

**Comment by darrenjs** [comment]
> You're welcome. Thanks for the script!
> 
> Incidentally, I wound up installing GCC 9.4.0 (on my Ubuntu 18.04 development computer) rather than using your script to build GCC 9.5.0. I successfully built GCC 9.5.0 with your script, but I was not confident I could install GCC 9.5.0 in the various system folders so it would be as if I had installed it from a standard Ubuntu repository via Apt.
> 
> But even after installing GCC 9.4.0 using [this procedure](https://gist.github.com/alexandreelise/192a63e287018ddfc896bbcb70b219d4) my application runs only on _some_ Linux distributions, while it fails to initialize on other versions of Linux such as Ubuntu 18.04. I suspect this is due to outdated libstdc++.so versions on the target system. Perhaps I need to statically link to the newer libstdc++ that comes with GCC 9.4.0, or somehow modify my .deb installer to fetch the newer libstdc++ as an installation dependency. I am pretty clueless about either approach.
> 
> I'd be grateful for any suggestions.
> 
> Thanks again.

Hi.  This script is not intended to install GCC into system locations,  it's aim is to have a new compiler live alongside the system default one. 

If you are trying to build using gcc 9.4 and then distribute your built artifacts to other systems, then I think you will indeed face the problems you suggest -- the target Linux systems won't have your gcc 9.4 libraries (eg, libstdc++ but also libgcc_s).  Two ways around this are to either (1) link statically and (2) distribute libstdc++ & libgcc_s belonging to gcc 9.4 with your program, and ensuring they are linked at runtime, ahead of the default system versions).       I would probably give (1) a go first, although it is not without its own challenges and problems.

**Pull request merged**
